### ISSUE TITLE
plotman won't stop plotting to a hard-drive that's nearly full

### ISSUE THREAD

**Issue by mc19000** [ericaltendorf/plotman#176] opened 2021-04-27 11:59 UTC
I have tried the current branch and reinstalled the development branch. I am running ubuntu 20.04.

My 1st HD has 504GB free, with 10 plots currently being plotted.
My 2nd HD has 10.6TB free, also with 10 plots active.

As you can see, my 1st HD should only have 4-5 active plots, as plotman should be detecting that it's nearly full and hence stop plotting there? I have tried killing plots over 5 which are going there, but plotman continues to keep trying to plot them into HD1. 

Is there a solution to this? I have 14 active plotters running plotman - I don't see a solution apart from manually keeping an eye on them and removing the hard-drive from the config file once full - then kill all plots that are going there.

Thanks

**Comment by ericaltendorf** [comment] 2021-04-27 14:58
Plotman currently assumes you use archiving to move plots from your
plotters to farming locations.  If you don't, you need to do this
manually.  If your plot destination dirs are directly your farming
locations then you need to stop plotman manually when they get full.  There
are feature requests for improving plotmans functionality in these cases;
they just aren't what it was originally developed for.

For now, if you are plotting directly to a farming location of fixed size,
you may be better off just scripting a bunch of plot invocations that will
fill that particular drive.

**Comment by savager** [comment] 2021-04-30 21:04
This is concerning. What happens if I don't manually stop plotman?

**Comment by altendky** [comment] 2021-05-01 00:15
If you use plotman other than intended and the dst dirs fill up then the plot processes writing to the full dst dirs will hang waiting for free space.  I think they sleep and recheck every five minutes or something.  Those processes will count against the plotman tmp dir max and global max limits so plotman will stop launching jobs when those limits tell it to.  At this point I just have dst as tmp and use archiving to get to the final locations.

**Comment by savager** [comment] 2021-05-01 00:31
I don't know if it's unintended to fill up the dst directory. Perhaps mounting the primary dest storage as NFS to all the plotters isn't standard but it should be fine. It is afterall just a quota bound zfs dataset in my case. But nonetheless, this seems acceptable, I'll just be hiking the ice age trail right when plotman is scheduled to have plotted all my drive space. I can live with this. thanks. thanks for the info!

**Comment by mikehw** [comment] 2021-05-09 12:49
This is addressed in PR #122 with a new optional configuration point. It’s been merged into the development branch but hasn’t made it’s way to main yet.

**Comment by altendky** [comment] 2021-05-12 13:27
Yes, not using the mechanism (archiving) that provides the feature you want (plot distribution) is an unintended use.  Archive can be used with nfs mounted archive directories.  Yes, it is a pain presently.  Yes we are working on improving the archiving configuration.

I'm sorry if I come across as a bit frustrated.  Merely searching for 'full' turns up five tickets right now related to this and I generally end up fielding a couple more daily on keybase (not to mention those that other people deal with).  So, instead of improving things I have to keep explaining how the desired feature exists already.

If you don't want the dst layer then the solution is to not have the dst layer, not to skip the archive layer that has the feature you want.  This can already be done with a single tmp drive by setting dst to tmp.  There is a PR to enable doing it with multiple tmp drives as well.

**Closed by altendky** 2021-05-12 13:27 UTC
Labels: enhancement

**Comment by savager** [comment] 2021-05-12 13:48
Oh, no, I'm sorry if I've frustrated you at all. I think maybe my intention has been misconstrued. I was simply curious if I had to implement my own method to stop plotman when my dst fills. I know I'm not using it as intended and I'm sorry, I was just kind of curious how it would fail. Thanks for everything.

**Comment by altendky** [comment] 2021-05-12 14:19
All good, I'm trying to make what I see as 'the right way' also be 'the obvious way' and 'the easy way' for everyone else.  Step by step.
