### ISSUE TITLE
chia-blockchain 1.1.5 requires click==7.1.2, but you have click 8.0.0 which is incompatible

### ISSUE THREAD

**Issue by btater** [ericaltendorf/plotman#370] opened 2021-05-12 19:59 UTC
I am having a very strange error on a fresh install of Chia Blockchain and then Plotman.  I can't find any root cause of this and has brought down 2 machines at this point.  Any pointers?

When I install plotman with "pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main"

It starts the install, and then gives this error:
"**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chia-blockchain 1.1.5 requires click==7.1.2, but you have click 8.0.0 which is incompatible."**

Any tips??

**Comment by JustinGuese** [comment] 2021-05-12 20:00
exactly the same issue

**Comment by btater** [comment] 2021-05-12 20:13
> exactly the same issue
> 
> is related to running plotman interactive
> 
> ```
> Traceback (most recent call last):
>   File "/home/df/chia-blockchain/venv/bin/plotman", line 8, in <module>
>     sys.exit(main())
>   File "/home/df/chia-blockchain/venv/lib/python3.8/site-packages/plotman/plotman.py", line 173, in main
>     interactive.run_interactive()
>   File "/home/df/chia-blockchain/venv/lib/python3.8/site-packages/plotman/interactive.py", line 334, in run_interactive
>     curses.wrapper(curses_main)
>   File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
>     return func(stdscr, *args, **kwds)
>   File "/home/df/chia-blockchain/venv/lib/python3.8/site-packages/plotman/interactive.py", line 180, in curses_main
>     dst_report = reporting.dst_dir_report(
>   File "/home/df/chia-blockchain/venv/lib/python3.8/site-packages/plotman/reporting.py", line 165, in dst_dir_report
>     priority = archive.compute_priority(eldest_ph, gb_free, n_plots) 
>   File "/home/df/chia-blockchain/venv/lib/python3.8/site-packages/plotman/archive.py", line 65, in compute_priority
>     if (phase.known):
> AttributeError: 'tuple' object has no attribute 'known'
> -´´´
> ```

Have you found a fix?

**Comment by JustinGuese** [comment] 2021-05-12 20:15
nope, it worked some hours back, so I guess it is an error in recent commits in either chia or plotman

**Comment by JustinGuese** [comment] 2021-05-12 20:19
@btater  got it!

```
pip uninstall click
chia -h # will fail
pip install click==7.1.2
chia init
plotman interactive
```

**Comment by altendky** [comment] 2021-05-12 20:27
Duplicate of https://github.com/ericaltendorf/plotman/issues/357.

**Closed by altendky** 2021-05-12 20:27 UTC
