### ISSUE TITLE
Madmax plotter

### ISSUE THREAD

**Issue by gabrialm** [ericaltendorf/plotman#796] opened 2021-06-17 21:34 UTC
**Describe the request**
Integrating the madmax plotter as an option to be selected I believe is a natural and necessary feature needed to keep Plotman relevant. I had a look through the open pull and feature requests, but saw nothing regarding this topic. Madmax allows older hardware to get relevant results (sub 1 hour plot creation times) and sub 30 minute creation times on modern hardware.

**Additional comments**
Swar manager has a fork in which this task is being undertaken, however the primary Swar project looks like its on the ropes to being abandoned, and Plotman appears to be far more feature rich and actively developed.

Edit: Madmax repo: https://github.com/madMAx43v3r/chia-plotter

**Comment by SauravKumal** [comment] 2021-06-18 05:18
yeah. love to see this feature

**Comment by guydavis** [comment] 2021-06-18 14:10
Yes!  See PR #797.  However, this Issue looks like a duplicate of #762 from last week.

**Comment by altendky** [comment] 2021-06-19 01:39
Thanks for the crosslink.  Closing this as a duplicate (yeah, I know, piles of other dpulicates I haven't gotten to closing...).  But yeah, presumably this will happen.  (or has happened... `:]` haven't gotten to looking at the PR yet)

**Closed by altendky** 2021-06-19 01:39 UTC
Labels: enhancement
